[tool.briefcase]
project_name = "HackRTH"
bundle = "com.rth.hackrth"
version = "0.0.1"
url = "https://github.com/lokkochan/HackRTH"
license = "MIT license"
author = 'rth'
author_email = "yuecheng.sun@ucalgary.ca"

[tool.briefcase.app.hackrth]
formal_name = "HackRTH"
description = "Try to create an Andriod app"
icon = "src/hackrth/resources/hackrth"
sources = ['src/hackrth']
requires = [
]


[tool.briefcase.app.hackrth.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.hackrth.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.hackrth.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.hackrth.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.hackrth.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.hackrth.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.hackrth.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.hackrth.web]
requires = [
    'toga-web>=0.3.0.dev38'
]
style_framework = "Bootstrap v4.6"
